---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildwest
  namespace: wildwest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wildwest
  template:
    metadata:
      labels:
        app: wildwest
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: wildwest
        image: ghcr.io/danielhelfand/gitops-app-repo@sha256:90416f3e85a5395a5a818deb364d0d16b53562f59fee4f971930649735fa7486
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
